name-template: 'scala-dropwizard-v$RESOLVED_VERSION'
tag-template: 'scala-dropwizard-v$RESOLVED_VERSION'
tag-prefix: scala-dropwizard-v
include-paths:
  - "modules/scala-dropwizard/"
  - "build.sbt"
  - "project/src/main/scala/modules/scalaDropwizard.scala"
# NB: Managed by support/regenerate-release-drafter.sh
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to $CONTRIBUTORS for your contributions to this release!
