codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 22  # This should match all code build tasks in the matrix, to instruct codecov to keep the submission window open long enough for all reporters to get in.
                        # Currently:
                        # - core :  1 build : javas: [15], scalas: [2.12]
                        # - java :  5 builds: javas: [8,11,13,14,15], scalas: [2.12]
                        # - scala: 16 builds: javas: [8,15], scalas: [2.12, 2.13], frameworks: [akka-http, akka-http-jackson, http4s, dropwizard]
                        #          22 builds in total
coverage:
  precision: 2
  round: down
  range: "81...90"

  status:
    project:
      default:
        target: 81%
        if_ci_failed: error
