swagger: '2.0'
host: localhost:1234
schemes:
- http
paths:
  /{path}:
    delete:
      operationId: deleteFoo
      parameters:
      - name: path
        in: path
        type: string
        required: true
      - name: query
        in: query
        type: string
        required: true
      - name: form
        in: formData
        type: string
        required: true
      consumes:
      - application/x-www-form-urlencoded
      responses:
        '204':
          description: No content
