swagger: "2.0"
info:
  title: 'Content-Type: text/plain spec'
  version: 1.0.0
host: localhost:1234
paths:
  /foo:
    post:
      operationId: doFoo
      x-jvm-package: foo
      consumes:
        - text/plain
      produces:
        - text/plain
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        201:
          description: "Created"
          schema:
            type: string
        406:
          description: "Invalid"
  /bar:
    post:
      operationId: doBar
      x-jvm-package: foo
      consumes:
        - text/plain
      produces:
        - text/plain
      parameters:
      - in: body
        name: body
        schema:
          type: string
      responses:
        201:
          description: "Created"
          schema:
            type: string
        406:
          description: "Invalid"
  /baz:
    post:
      operationId: doBaz
      x-jvm-package: foo
      consumes:
        - text/plain
      produces:
        - text/plain
      parameters:
        - in: body
          name: body
          schema:
            type: string
      responses:
        201:
          description: "Created"
          schema:
            type: string
        406:
          description: "Invalid"
