swagger: '2.0'
info:
  title: Polymorphism nested example
  version: 1.0.0
produces:
  - application/json
paths:
  /foo:
    get:
      operationId: getPet
      parameters:
        - name: Status
          in: formData
          type: string
        - name: a
          in: body
          schema:
            $ref: '#/definitions/Option'
        - name: b
          in: body
          schema:
            $ref: '#/definitions/List'
        - name: c
          in: body
          schema:
            $ref: '#/definitions/IndexedSeq'
      responses:
        200:
          description: "adasd"
          schema:
            $ref: '#/definitions/Option'
definitions:
  Option:
    properties:
      value:
        type: number
  List:
    properties:
      value:
        type: number
  IndexedSeq:
    properties:
      value:
        type: number
      
