swagger: '2.0'
info:
  title: Parsing Error Sample
  version: 1.0.0
paths:
  /pet/{name}:
    get:
      operationId: getPet
      parameters:
        - $ref: '#/parameters/PetNamePathParam'
      responses:
        200:
          description: Return the details about the pet
          schema:
            $ref: '#/definitions/Pet'
parameters:
  PetNamePathParam:
    name: name
    description: Unique name of the pet
    in: path
    type: string
    required: true
definitions:
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
    - petType
  Cat:
    description: A representation of a cat
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        huntingSkill:
          type: string
          description: The measured skill for hunting
          default: lazy
          enum:
          - clueless
          - lazy
          - adventurous
          - aggressive
      required:
      - huntingSkill
  Dog:
    description: A representation of a dog
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        packSize:
          type: integer
          format: int32
          description: the size of the pack the dog is from
          default: 0
          minimum: 0
      required:
      - packSize
