name: "Pull Request Labeler"
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Label scala-steward
        run: ./support/label-scala-steward-prs.sh "${{ secrets.GITHUB_TOKEN }}"
  cron-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Labeler
        uses: fjeremic/cron-labeler@0.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
